### ISSUE TITLE
Unnecessary classnames

### ISSUE THREAD

**Issue by denterekhov** [Lectrum/react-personal-project#5]
В snapshot'е компонента Scheduler проверяется наличие класса createTask у input'а  
https://github.com/Lectrum/react-personal-project/blob/07e02cf869a10ac70719d7c6c08ca1235d7a81db/source/components/Scheduler/tests/__snapshots__/Scheduler.test.js.snap#L32 и класса overlay у div'а https://github.com/Lectrum/react-personal-project/blob/07e02cf869a10ac70719d7c6c08ca1235d7a81db/source/components/Scheduler/tests/__snapshots__/Scheduler.test.js.snap#L44 Эти классы отсутствуют в css, поэтому их можно убрать. Последний div можно удалить совсем.

**Comment by dvakatsiienko** [comment]
closed by #6
